[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"
buildCommand = "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[build.env]
PYTHON_VERSION = "3.12.8"

