services:
  - type: web
    name: mlwebsite
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true

