services:
  - type: web
    name: mlwebsite
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary numpy==1.26.4 scipy==1.12.0 scikit-learn==1.4.1 && pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true

